# Generated by Django 5.2.7 on 2025-10-22 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ku_token', '0001_initial'),
        ('task', '0004_alter_task_claimed_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='task.task'),
        ),
    ]
