# Generated by Django 5.2.7 on 2025-10-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'News'},
        ),
        migrations.RenameField(
            model_name='news',
            old_name='featured_image',
            new_name='image1',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='views_count',
            new_name='likes_count',
        ),
        migrations.RemoveField(
            model_name='news',
            name='excerpt',
        ),
        migrations.RemoveField(
            model_name='news',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='news',
            name='published_at',
        ),
        migrations.RemoveField(
            model_name='news',
            name='slug',
        ),
        migrations.AddField(
            model_name='news',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='news/'),
        ),
    ]
