# Generated by Django 5.2.7 on 2025-11-21 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_rename_address_userprofile_bio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="region",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.region",
            ),
        ),
    ]
