# Generated by Django 5.2.7 on 2025-10-18 18:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("mining", "Mining Reward"),
                            ("referral", "Referral Bonus"),
                            ("task", "Task Completion"),
                            ("bonus", "Bonus"),
                            ("withdrawal", "Withdrawal"),
                            ("transfer", "Transfer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=4, max_digits=20)),
                ("description", models.CharField(max_length=255)),
                ("reference_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "balance_before",
                    models.DecimalField(decimal_places=4, max_digits=20),
                ),
                ("balance_after", models.DecimalField(decimal_places=4, max_digits=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="transaction_user_id_d29ed6_idx",
                    ),
                    models.Index(
                        fields=["transaction_type"],
                        name="transaction_transac_33a64a_idx",
                    ),
                ],
            },
        ),
    ]
