# Generated by Django 5.2.7 on 2025-10-18 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_global', models.IntegerField(default=0)),
                ('rank_regional', models.IntegerField(default=0)),
                ('total_earnings', models.DecimalField(decimal_places=4, max_digits=20)),
                ('team_size', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entry', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['rank_global'],
                'indexes': [models.Index(fields=['rank_global'], name='leaderboard_rank_gl_f92f36_idx'), models.Index(fields=['rank_regional'], name='leaderboard_rank_re_595273_idx')],
            },
        ),
    ]
