# Generated by Django 5.2.7 on 2025-10-22 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(blank=True, max_length=250, null=True)),
                ('region_codle', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_global', models.IntegerField(default=0)),
                ('total_earnings', models.DecimalField(decimal_places=4, max_digits=20)),
                ('team_size', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='global_leaderboard', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['rank_global'],
            },
        ),
        migrations.CreateModel(
            name='RegionalLeaderBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_regional', models.IntegerField(default=0)),
                ('total_earnings', models.DecimalField(decimal_places=4, max_digits=20)),
                ('team_size', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leaderboard.region')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='regional_leaderboard', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['rank_regional'],
            },
        ),
        migrations.DeleteModel(
            name='Leaderboard',
        ),
        migrations.AddIndex(
            model_name='globalleaderboard',
            index=models.Index(fields=['rank_global'], name='leaderboard_rank_gl_59ad5d_idx'),
        ),
        migrations.AddIndex(
            model_name='regionalleaderboard',
            index=models.Index(fields=['rank_regional'], name='leaderboard_rank_re_0fdf92_idx'),
        ),
    ]
