# Generated by Django 5.2.7 on 2025-10-22 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0004_alter_globalleaderboard_total_earnings_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regionalleaderboard',
            options={'ordering': ['-total_earnings']},
        ),
    ]
