# Generated by Django 5.2.7 on 2025-10-21 16:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_rename_task_type_task_category_delete_usertask'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='claimed_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
