# Generated by Django 5.2.7 on 2025-10-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_task_claimed_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='task/'),
        ),
    ]
