# Generated by Django 5.2.7 on 2025-10-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaderboard", "0003_alter_globalleaderboard_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="globalleaderboard",
            name="total_earnings",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="regionalleaderboard",
            name="total_earnings",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
    ]
