# Generated by Django 5.2.7 on 2025-10-22 18:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaderboard", "0002_region_globalleaderboard_regionalleaderboard_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="globalleaderboard",
            options={"ordering": ["total_earnings"]},
        ),
        migrations.AlterModelOptions(
            name="regionalleaderboard",
            options={"ordering": ["total_earnings"]},
        ),
        migrations.RemoveIndex(
            model_name="globalleaderboard",
            name="leaderboard_rank_gl_59ad5d_idx",
        ),
        migrations.RemoveIndex(
            model_name="regionalleaderboard",
            name="leaderboard_rank_re_0fdf92_idx",
        ),
        migrations.AddIndex(
            model_name="globalleaderboard",
            index=models.Index(
                fields=["total_earnings"], name="leaderboard_total_e_4c0c5f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="regionalleaderboard",
            index=models.Index(
                fields=["total_earnings"], name="leaderboard_total_e_c7ca1c_idx"
            ),
        ),
    ]
