# Generated by Django 5.2.7 on 2025-11-16 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ku_token", "0003_alter_token_task"),
    ]

    operations = [
        migrations.RenameField(
            model_name="token",
            old_name="total_token",
            new_name="quantity",
        ),
        migrations.RemoveField(
            model_name="token",
            name="task",
        ),
    ]
