# Generated by Django 5.2.7 on 2025-10-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_alter_news_options_rename_featured_image_news_image1_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="news",
            old_name="image1",
            new_name="image",
        ),
        migrations.RemoveField(
            model_name="news",
            name="image2",
        ),
        migrations.AddField(
            model_name="news",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
